# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('team', models.BooleanField(default=False)),
                ('judge', models.CharField(choices=[('all', 'All'), ('uri', 'URI'), ('uva', 'UVa'), ('spoj', 'SPOJ')], default='all', max_length=4)),
                ('B', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('D', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=500)),
                ('secret_key_user', models.CharField(max_length=100)),
                ('secret_key_coach', models.CharField(blank=True, max_length=100)),
                ('secret_key_visitor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('solved', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('judge', models.CharField(choices=[('uri', 'URI'), ('uva', 'UVa'), ('spoj', 'SPOJ')], max_length=4)),
                ('category', models.CharField(choices=[('B', 'Beginner'), ('A', 'Ad-Hoc'), ('S', 'Strings'), ('D', 'Data Structures and Libraries'), ('M', 'Mathematics'), ('P', 'Paradigms'), ('G', 'Graph'), ('C', 'Computational Geometry'), ('U', 'Uncategorized')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('facebookId', models.CharField(max_length=100)),
                ('uriId', models.CharField(blank=True, max_length=50)),
                ('uvaId', models.CharField(blank=True, max_length=50)),
                ('spojId', models.CharField(blank=True, max_length=50)),
                ('uri_authorization', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('coach', 'Coach'), ('visitor', 'Visitor')], default='user', max_length=7)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='home.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Problem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profiles', models.ManyToManyField(related_name='teams', to='home.Profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='home.Team'),
        ),
        migrations.AddField(
            model_name='group',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='home.Institution'),
        ),
        migrations.AddField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='home.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='profiles',
            field=models.ManyToManyField(related_name='contests', to='home.Profile'),
        ),
        migrations.AddField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(related_name='contests', to='home.Team'),
        ),
    ]
