# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='team',
            field=models.BooleanField(default=False),
        ),
    ]
