# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170509_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('coach', 'Coach'), ('visitor', 'Visitor')], default='user', max_length=7, null=True),
        ),
    ]
