# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160430_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(related_name='contests', to='home.Team'),
        ),
    ]
