# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contest_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='judge',
            field=models.CharField(choices=[('uri', 'URI'), ('uva', 'UVa'), ('spoj', 'SPOJ')], default='uri', max_length=4),
        ),
        migrations.AlterField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='home.Team'),
        ),
    ]
