# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160613_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='contest',
            name='judge',
            field=models.CharField(choices=[('all', 'All'), ('uri', 'URI'), ('uva', 'UVa'), ('spoj', 'SPOJ')], default='all', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
