# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170506_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='secret_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
