# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170506_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='secret_key',
            new_name='secret_key_user',
        ),
    ]
