# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170506_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('coach', 'Coach'), ('visitor', 'Visitor')], default='user', max_length=7),
        ),
    ]
