# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='uri_authorization',
            field=models.BooleanField(default=False),
        ),
    ]
