# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('solved', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('judge', models.CharField(choices=[(b'uri', b'URI'), (b'uva', b'UVA'), (b'spoj', b'SPOJ')], default=b'uri', max_length=4)),
                ('category', models.CharField(choices=[(b'B', b'Beginner'), (b'A', b'Ad-Hoc'), (b'S', b'Strings'), (b'D', b'Data Structures and Libraries'), (b'M', b'Mathematics'), (b'P', b'Paradigms'), (b'G', b'Graph'), (b'C', b'Computational Geometry'), (b'U', b'Uncategorized')], default=b'U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facebookId', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=500)),
                ('uriId', models.CharField(blank=True, max_length=50)),
                ('uvaId', models.CharField(blank=True, max_length=50)),
                ('spojId', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Problem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
    ]
