# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('B', 'Beginner'), ('A', 'Ad-Hoc'), ('S', 'Strings'), ('D', 'Data Structures and Libraries'), ('M', 'Mathematics'), ('P', 'Paradigms'), ('G', 'Graph'), ('C', 'Computational Geometry'), ('U', 'Uncategorized')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='judge',
            field=models.CharField(choices=[('uri', 'URI'), ('uva', 'UVA'), ('spoj', 'SPOJ')], default='uri', max_length=4),
        ),
        migrations.AlterField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
