# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(related_name='contests', to='home.Profile'),
        ),
    ]
