# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160324_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='D',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='M',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='P',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='S',
            field=models.IntegerField(default=0),
        ),
    ]
