# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contest_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profiles',
            field=models.ManyToManyField(related_name='teams', to='home.Profile'),
        ),
    ]
