# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160324_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='G',
            field=models.IntegerField(default=0),
        ),
    ]
